### ISSUE TITLE
No Functionality on Membership Pages

### ISSUE THREAD

**Issue by hair-transplant** [twomice/com.joineryhq.percentagepricesetfield#23]
We are using 1.2beta6/ CiviCRM 4.7.29 / Joomla with european data (that means , = decimal point)

The module works in event page and in a standard fee page, but not connected to membership

![mwsnap195](https://user-images.githubusercontent.com/35275822/35751609-784c3510-0859-11e8-8eec-177cb4342517.jpg)
![mwsnap196](https://user-images.githubusercontent.com/35275822/35751611-7869ef92-0859-11e8-9535-ff6678aa4276.jpg)

Actually here the choice should not be given.

There is a JS error
![mwsnap197](https://user-images.githubusercontent.com/35275822/35751927-6cb57f12-085a-11e8-8042-c356ae733515.jpg)

Seems to be connected to CIVIDISCOUNT, why it does work on the event page and not on the membership page is unclear to me

**Comment by twomice** [comment]
Clearly I have neglected this issue for a long time. I believe that in the interim, this issue has been resolved, or perhaps there is more detail I will need in order to reproduce it. Here's a screenshot of a Membership page in Joomla using the 'Hide Checkbox and Force to "yes"' setting on the Percentage Price Set Field:
![j](https://github.com/user-attachments/assets/62c11dcc-e163-4aed-a247-a0502651b016)

The above screenshot is taken while using the latest release of this extension, v1.5.3 (released today). 

With all that in mind, I'll close this issue for now. If you're still interested in this issue and think it needs more attention, please try in this latest version, and then feel free to re-open this issue with details about the problem you're seeing. Thanks @hair-transplant !
