### ISSUE TITLE
contribution (Stripe payment) fails when percentage field is enabled

### ISSUE THREAD

**Issue by MtnPavlas** [twomice/com.joineryhq.percentagepricesetfield#55]
Cross-posting here as I'm not sure if it's % field or Stripe Pmt extension or CiviCRM core issue : (

https://lab.civicrm.org/extensions/stripe/-/issues/465

Thank you so much for any pointers.

**Comment by kcristiano** [comment]
adding my notes - https://lab.civicrm.org/extensions/stripe/-/issues/465#note_162573

**Comment by MtnPavlas** [comment]
Hello, any progress on this please? Thank you so much.

**Comment by twomice** [comment]
Confirmed: I can reproduce this under v1.5.2 (the current latest release). Working on a solution now. Thanks @MtnPavlas for the report!

**Comment by twomice** [comment]
This has been fixed by 606aa53, which also fixes "Always adding $1 and calculating based on that additional amount" (#57).

I've tested this on my own live site. If anyone here could test the latest master and report back, that would be helpful, but either way I expect to tag a new release this week.

Thanks @konadave and @kcristiano for your additional insights!

**Comment by twomice** [comment]
I'll go ahead and close this, as I believe it's fixed in today's release of version 1.5.3. Please feel free to re-open if you believe it still needs attention under that version. Thanks!
